### ISSUE TITLE
issue with async storage

### ISSUE THREAD

**Issue by vm1000** [internship-guidance/counter#1]
when I import async storage like other react native elements, it shows me error like this:

<img width="484" alt="Screenshot 2019-06-10 at 15 16 26" src="https://user-images.githubusercontent.com/41584015/59195072-b3880500-8b93-11e9-92bb-25bdcaf34bb0.png">

as I understand async storage is renamed, but I am not able to import new version of it.

**Comment by a-uz** [comment]
@vm1000 AsyncStorage that comes from 'react-native' is deprecated and is no longer supported (that's why you see this warning). The latest version is available [here](https://github.com/react-native-community/react-native-async-storage).

This is part of the React Native's project ([Lean Core](https://github.com/facebook/react-native/issues/23313)) I told you about
